// Verilator C++ TB for lif_step.v — gold vectors from FixedPointLIF (陈正共 / G3)
// Include auto-generated by: python3 scripts/phase4_fpga_gen_lif_golden_vectors.py
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include "Vlif_step.h"
#include "verilated.h"
#include "lif_step_golden_vectors.inc"

static void tick(Vlif_step* top) {
    top->clk = 0;
    top->eval();
    top->clk = 1;
    top->eval();
}

static int run_one(Vlif_step* top, int32_t cur, int32_t mem_in, int32_t* spk, int32_t* mem_out) {
    top->start = 0;
    top->cur_q16 = cur;
    top->mem_in_q16 = mem_in;
    tick(top);
    top->start = 1;
    tick(top);
    top->start = 0;
    // hard mul: ~3 cycles; soft (lif_step_open): ~35 cycles
    for (int i = 0; i < 64; i++) {
        tick(top);
        if (top->done) {
            *spk = top->spk_out ? 1 : 0;
            *mem_out = (int32_t)top->mem_out_q16;
            return 0;
        }
    }
    return 1;
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vlif_step* top = new Vlif_step;

    top->rst_n = 0;
    top->start = 0;
    top->cur_q16 = 0;
    top->mem_in_q16 = 0;
    for (int i = 0; i < 4; i++) tick(top);
    top->rst_n = 1;
    tick(top);

    int mismatches = 0;
    for (int i = 0; i < GOLDEN_N; i++) {
        int32_t sr, mr;
        if (run_one(top, GOLDEN_CUR[i], GOLDEN_MEM_IN[i], &sr, &mr) != 0) {
            std::fprintf(stderr, "TIMEOUT i=%d\n", i);
            mismatches++;
            continue;
        }
        if (sr != GOLDEN_SPK[i] || mr != GOLDEN_MEM_OUT[i]) {
            std::fprintf(stderr,
                "MISMATCH i=%d cur=%d mem_in=%d gold_spk=%d rtl_spk=%d gold_mem=%d rtl_mem=%d\n",
                i, GOLDEN_CUR[i], GOLDEN_MEM_IN[i], GOLDEN_SPK[i], sr, GOLDEN_MEM_OUT[i], mr);
            mismatches++;
        }
    }

    delete top;
    if (mismatches) {
        std::printf("FAIL mismatches=%d golden=FixedPointLIF\n", mismatches);
        return 1;
    }
    std::printf("PASS verilator lif_step n=%d mismatches=0 golden=FixedPointLIF\n", GOLDEN_N);
    return 0;
}
